version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: meu_postgres
    restart: always
    ports:
      - "1234:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: polls
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
